CREATE SCHEMA IF NOT EXISTS STORE;
SET SCHEMA STORE;
CREATE TABLE BRAND (ID INTEGER PRIMARY KEY NOT NULL,NAME VARCHAR(50) NOT NULL);
CREATE TABLE PRODUCT (ID INTEGER PRIMARY KEY NOT NULL,NAME VARCHAR(50) NOT NULL);
CREATE TABLE PRICE (ID INTEGER PRIMARY KEY NOT NULL, BRAND_ID INTEGER NOT NULL, START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL, PRICE_LIST INTEGER NOT NULL, PRODUCT_ID INTEGER NOT NULL, PRIORITY INTEGER NOT NULL,
PRICE NUMERIC(4,2) NOT NULL, CURR VARCHAR(10) NOT NULL, CONSTRAINT FK_PRICE_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID),
CONSTRAINT FK_PRICE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID));